### ISSUE TITLE
[NHF-011] Create login page

### ISSUE THREAD

**Issue by chrisdevindev** [NEIGHBOR-HUB/neighbor-HUB-frontend#16]
## Create the login page with its form and its following features:

1. The login page is static until there is an endpoint on the backend to login;
2. The login page is the first page of application;

## Prototype
![Login](https://user-images.githubusercontent.com/47678397/196607677-6a732f8c-3def-4bc5-9418-c5850bd38b04.png)

https://www.figma.com/proto/OXedGSjkxsZNuXHwrhDZHG/Nhub?node-id=35%3A1015&scaling=min-zoom&page-id=35%3A778

**Comment by siyaa12** [comment]
Can I work on this issue ?

**Comment by avezqureshi14** [comment]
Hey @CCastro01 can you assign me this issue
