### ISSUE TITLE
[NHF-012] Create register page 

### ISSUE THREAD

**Issue by chrisdevindev** [NEIGHBOR-HUB/neighbor-HUB-frontend#17]
## Create the register page with its form and its following features:

1. The register page is static until there is an endpoint on the backend to login;
2. The register page is called when "Cadastre-se" is clicked in login page;

> This task should be done when the login page is complete.

## Prototype
![Cadastro](https://user-images.githubusercontent.com/47678397/196608931-87a83f0a-388e-445b-8216-54b449c4e1d7.png)

https://www.figma.com/proto/OXedGSjkxsZNuXHwrhDZHG/Nhub?node-id=35%3A1061&scaling=min-zoom&page-id=35%3A778

**Comment by avezqureshi14** [comment]
Hey @CCastro01 can you assign this to me
