### ISSUE TITLE
[NHF-013] Create Forgot Password component

### ISSUE THREAD

**Issue by chrisdevindev** [NEIGHBOR-HUB/neighbor-HUB-frontend#18]
## Create the Forgot Password component with its following features:

1. The Forgot Password component is static until there is an endpoint on the backend to send a url to user access the Change Password component ;

> This task should be done when the login page is complete.

![Senha](https://user-images.githubusercontent.com/47678397/196612345-b39d0a9b-c9b1-47bc-b1ce-713f5f72af69.png)
![Senha (1)](https://user-images.githubusercontent.com/47678397/196612354-b23b2081-31aa-4f0b-bb0b-6a26f9b3e9a0.png)

https://www.figma.com/file/OXedGSjkxsZNuXHwrhDZHG/Nhub?node-id=35%3A1144

**Comment by harisaisundhar** [comment]
Can I get this assigned ?
